### ISSUE TITLE
Add "Gallery" Shield

### ISSUE THREAD

**Issue by WieFel** [WieFel/gallerize#3]
Add "Gallery" Shield which users can put in their README (https://shields.io/)

**Comment by WieFel** [comment]
@daadu what do you think of the badge?
[![gallerize](https://img.shields.io/badge/gallerize-show%20demo-purple?logo=flutter&logoColor=blue)](https://github.com/WieFel/gallerize)

**Comment by daadu** [comment]
It's good. can we make it `check demo`?

**Comment by WieFel** [comment]
Sure, will do
