### ISSUE TITLE
Github Pages + Github Action Setup

### ISSUE THREAD

**Issue by WieFel** [WieFel/gallerize#4]
Github Pages + Github Action Setup - to host the example project, with CD - any push to master branch triggers flutter build web
-> commit/create PR to gh-pages branch
-> changes reflected to "Github Pages"

**Comment by WieFel** [comment]
1. Made `example/` project flutter-web compatible.
2. Created `gh-pages` branch

However, example project is not served on https://wiefel.github.io/gallerize/example/
Any ideas what I did wrong, @daadu ?

**Comment by daadu** [comment]
this is the root of project: https://wiefel.github.io/gallerize/

**Comment by WieFel** [comment]
Yes I know. But how did you manage `backdrop/demo` site to be published on https://fluttercommunity.github.io/backdrop/demo/#/ ?
Here in gallerize, only the `example/` subfolder is the one we are interested in, similar to `demo/` in backdrop.

**Comment by daadu** [comment]
If you check the `gh-pages` branch (https://github.com/fluttercommunity/backdrop/tree/gh-pages) properly it is just html files.

Create "empty" branch(remove the older one) - `git checkout --orphan gh-pages`. You will have to force push gh-pages after that.

add static web asset generated by `flutter build web` to it, you can use directory `example` to have its own static assets.

**Comment by WieFel** [comment]
@daadu thanks.
Done!
https://wiefel.github.io/gallerize/#/

**Comment by WieFel** [comment]
Still TODO: setup github action for deployment

**Comment by WieFel** [comment]
Done

**Comment by daadu** [comment]
I would say you put a guide in the readme, that can help package manager to setup GitHub Actions for CD for Github Pages.

**Comment by WieFel** [comment]
@daadu actually I was thinking of doing exactly that ;D
As I also couldn't find any medium article or similar talking about the combination of "flutter web + gh-pages branch" maybe I'll write a short article.

**Comment by WieFel** [comment]
@daadu what do you think?
https://github.com/WieFel/gallerize#automatically-publish-demo-app-flutter-web-on-github-pages

**Comment by daadu** [comment]
Looks good to me if it works!! Can we integrate this with backdrop?

**Comment by WieFel** [comment]
Yes, it is how I set it up with gallerize example itself ;) check gh-pages branch...

> Can we integrate this with backdrop?

Sure, you mean action for automatic deployment to gh-pages? I can set it up

**Comment by daadu** [comment]
> Sure, you mean action for automatic deployment to gh-pages? I can set it up

Yes.
