### ISSUE TITLE
Code is not selectable 

### ISSUE THREAD

**Issue by daadu** [WieFel/gallerize#5]

**Comment by WieFel** [comment]
Question is how to implement this?
[flutter_highlight](https://pub.dev/packages/flutter_highlight) is used for code highlighting, which apparently doesn't offer any option for text selection.

Also flutter gallery doesn't offer text selection. Their solution is to provide a "COPY ALL" button.
![gallery](https://user-images.githubusercontent.com/8345062/108601085-0ff87b80-739b-11eb-9671-8677b86a2e19.png)
@daadu What would you think of doing the same?

**Comment by daadu** [comment]
"copy button" is a good option if making text selectable is not implementable.

**Comment by WieFel** [comment]
It could be implemented using `FloatingActionButton`

**Comment by daadu** [comment]
do it as "gallery" does, that is why the package is named "gallerize" !
