### ISSUE TITLE
Add Showcase in README

### ISSUE THREAD

**Issue by daadu** [WieFel/gallerize#6]
This is to show "packages" that have "demo" site implemented with `gallerize`.

**Comment by WieFel** [comment]
Good idea! I have thought about this too.
Until now we have:
- backdrop
- gallerize
- [hsv_color_pickers](https://github.com/WieFel/hsv_color_pickers) (my package)

I will also add a reminder to people who use gallerize to report it back so that their package can be named within showcase section.
